language: node_js
node_js:
  - 12

# 배포 전 빌드하기
before_deploy:
  - if ! [[ $BEFORE_DEPLOY_RUN ]]; then
    export BEFORE_DEPLOY_RUN=1;
    npm run build;
    tar -zcvf app.tar.gz .// > /dev/null 2>&1;
    mkdir -p pre-deploy;
    mv app.tar.gz pre-deploy/app.tar.gz;
    mv appspec.yml pre-deploy/appspec.yml;
    tar -zcvf nestbnb-api.tar.gz ./pre-deploy;
    mkdir -p deploy;
    mv nestbnb-api.tar.gz deploy/nestbnb-api.tar.gz;
    fi
#> /dev/null 2>&1 # -x "./node_modules/*"

#zip -r nestbnb-api ./* /dev/null 2>&1 &&

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: nestbnb-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: nestbnb-build
    key: nestbnb-api.tar.gz

    bundle_type: tgz
    application: nestbnb-api

    deplyment_group: nestbnb-api-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hyeonss0417@gmail.com
