language: node_js
node_js:
  - 12

before_deploy:
  - npm run build
  - zip -r nestbnb-api ./dist
  - mkdir -p deploy
  - mv nestbnb-api.zip deploy/nestbnb-api.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: nestbnb-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: nestbnb-build
    key: nestbnb-api.zip

    bundle_type: zip
    application: nestbnb-api

    deplyment_group: nestbnb-api-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hyeonss0417@gmail.com
