version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nestjs-airbnb/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 1200
      runas: ubuntu
