export const DATABASE_CONNECTION_DEV = 'DATABASE_CONNECTION_DEV' as const;
export const DATABASE_CONNECTION_TEST = 'DATABASE_CONNECTION_TEST' as const;
export const DATABASE_CONNECTION_PROD = 'DATABASE_CONNECTION_PROD' as const;
export const PHOTO_REPOSITORY = 'PHOTO_REPOSITORY' as const;

